// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvzavxtebcqoysfehoze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52emF2eHRlYmNxb3lzZmVob3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzA2NzgsImV4cCI6MjA3MzAwNjY3OH0.c7eADLoDUZvmQbjkGsoyK9bwOD4_eM7yvEth-d-8gao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});